ALTER TABLE games ADD COLUMN IF NOT EXISTS region TEXT NOT NULL DEFAULT '';
ALTER TABLE metadata_submission_files DROP COLUMN IF EXISTS region;
ALTER TABLE media DROP COLUMN IF EXISTS region;
DROP TABLE IF EXISTS game_regions;
DROP TABLE IF EXISTS regions;
