// Package systems holds the official NeoAssets system catalog used to
// validate uploaded background/logo system ids and to serve the list to the
// web frontend.
package systems

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"sort"
)

// System is a single entry in the NeoAssets system catalog.
type System struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	ShortName string `json:"short_name"`
}

// systems.json is generated by cmd/sync-systems from the neostation-frontend
// repo (assets/systems/*.json). It is embedded at build time so the running
// service never needs network access.
//
//go:embed systems.json
var embedded []byte

// Catalog is an in-memory, read-only view of the system catalog.
type Catalog struct {
	list  []System
	byID  map[string]System
}

// Load parses the embedded systems.json into a Catalog.
func Load() (*Catalog, error) {
	var list []System
	if err := json.Unmarshal(embedded, &list); err != nil {
		return nil, fmt.Errorf("parse embedded systems.json: %w", err)
	}

	byID := make(map[string]System, len(list))
	for _, s := range list {
		byID[s.ID] = s
	}

	sort.Slice(list, func(i, j int) bool { return list[i].Name < list[j].Name })

	return &Catalog{list: list, byID: byID}, nil
}

// List returns the systems sorted by name.
func (c *Catalog) List() []System {
	return c.list
}

// Has reports whether the given id exists in the catalog.
func (c *Catalog) Has(id string) bool {
	_, ok := c.byID[id]
	return ok
}
