package services

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"regexp"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/rs/zerolog/log"
	"golang.org/x/time/rate"

	"neoassets/internal/models"
	"neoassets/internal/progression"
	"neoassets/internal/repository"
	"neoassets/pkg/auth"
)

// ErrQuotaExceeded is returned when a subject has consumed its daily quota.
var ErrQuotaExceeded = errors.New("daily scrape quota exceeded")

// Default scrape limits, overridable from the environment.
const (
	// defaultRPMPerThread is the per-minute request budget granted per scrape
	// thread: the effective RPM is threads * RPMPerThread (guest 2 -> 200,
	// admin 16 -> 1600). Threads already scale the daily quota.
	defaultRPMPerThread = 100

	// maxGamesLimit is how many candidates a name search scans to pick the best
	// single match.
	maxGamesLimit = 25

	defaultPopularLimit = 20
	maxPopularLimit     = 50

	// maxDebugCallsPerDay caps developer debug requests per app per day.
	maxDebugCallsPerDay = 100

	// maxSystemsPerRequest caps how many systems a family/group selector may
	// expand to, bounding the cost of a single request.
	maxSystemsPerRequest = 50

	// maxScrapeNameLen caps the cleaned name sent to the search, bounding the
	// number of LIKE predicates generated by tokenization.
	maxScrapeNameLen = 200
)

// ScrapeService authenticates scraping API consumers, enforces per-minute rate
// limits and the daily scrape quota, and serves the public catalog payloads.
type ScrapeService struct {
	repo      *repository.Repository
	meta      *Service // catalog reads (systems/games) reused from the web service
	jwtSecret string

	guestThreads int
	rpmPerThread int
	debugEnabled bool
	requireVerified bool

	mu       sync.Mutex
	limiters map[string]*limiterEntry
}

// limiterEntry pairs a token bucket with its last access time so stale entries
// can be evicted instead of resetting the whole map. rpm is kept so a bucket is
// rebuilt when a subject's thread count changes.
type limiterEntry struct {
	lim  *rate.Limiter
	rpm  int
	last time.Time
}

// NewScrapeService creates a ScrapeService. Non-positive values fall back to
// the defaults. The daily quota is per account and scales with the thread count
// (threads * DailyGamesPerThread), so more threads also means a bigger daily
// limit.
func NewScrapeService(repo *repository.Repository, meta *Service, jwtSecret string, guestThreads, rpmPerThread int, debugEnabled, requireVerified bool) *ScrapeService {
	if guestThreads <= 0 {
		guestThreads = repository.GuestThreads
	}
	if rpmPerThread <= 0 {
		rpmPerThread = defaultRPMPerThread
	}
	return &ScrapeService{
		repo:            repo,
		meta:            meta,
		jwtSecret:       jwtSecret,
		guestThreads:    guestThreads,
		rpmPerThread:    rpmPerThread,
		debugEnabled:    debugEnabled,
		requireVerified: requireVerified,
		limiters:        map[string]*limiterEntry{},
	}
}

// AuthenticateScrape resolves the two credential layers into a scrape subject.
// Developer app credentials are always required; the user credential is
// optional and falls back to guest mode. It also applies the per-minute rate
// limit for the resolved subject.
func (s *ScrapeService) AuthenticateScrape(ctx context.Context, creds auth.ScrapeCredentials) (*auth.ScrapeSubject, error) {
	if creds.ClientID == "" || creds.ClientSecret == "" {
		return nil, &auth.AuthError{
			Status:  http.StatusUnauthorized,
			Message: "missing developer credentials (X-Client-Id, X-Client-Secret)",
		}
	}

	app, err := s.repo.GetDeveloperAppByClientID(creds.ClientID)
	if err != nil {
		return nil, &auth.AuthError{Status: http.StatusUnauthorized, Message: "invalid developer credentials"}
	}
	if app.RevokedAt != nil {
		return nil, &auth.AuthError{Status: http.StatusForbidden, Message: "developer application revoked"}
	}
	if !auth.CheckTokenHash(creds.ClientSecret, app.SecretHash) {
		return nil, &auth.AuthError{Status: http.StatusUnauthorized, Message: "invalid developer credentials"}
	}
	// Avoid a write on every request: only refresh last_used_at when stale.
	if app.LastUsedAt == nil || time.Since(*app.LastUsedAt) > time.Minute {
		_ = s.repo.TouchDeveloperAppLastUsed(creds.ClientID)
	}

	// Enforce a generous per-app rate limit before resolving the optional user
	// credential, so a garbage user credential cannot force an unbounded DB
	// lookup without any throttling. The real per-subject limit is applied below.
	if !s.limiterFor("pre:"+app.ClientID, s.preCheckRPM()).Allow() {
		s.record(app.ID, resolveSoftwareName(creds.SoftwareName, app.Name), "rate_limited")
		return nil, &auth.AuthError{Status: http.StatusTooManyRequests, Message: "rate limit exceeded"}
	}

	subject := &auth.ScrapeSubject{
		Kind:          auth.ScrapeKindGuest,
		ClientID:      app.ClientID,
		ClientDBID:    app.ID,
		ClientName:    app.Name,
		ClientOwnerID: app.UserID,
		SoftwareName:  resolveSoftwareName(creds.SoftwareName, app.Name),
		Threads:       s.guestThreads,
		DailyLimit:    s.guestThreads * repository.DailyGamesPerThread,
	}

	if creds.UserCredential != "" {
		user, err := s.resolveUser(creds.UserCredential)
		if err != nil {
			return nil, err
		}
		threads := repository.ThreadsForUser(user.Role, user.DonorStatus, user.XP)
		subject.Kind = auth.ScrapeKindUser
		subject.UserID = user.ID
		subject.Username = user.Username
		subject.Threads = threads
		subject.DailyLimit = threads * repository.DailyGamesPerThread
	}

	// Developer debug mode: a valid debug password unlocks counter/limit
	// overrides, capped per day. It is gated by ENABLE_DEBUG_MODE and never
	// bypasses authentication.
	if s.debugEnabled && creds.DebugPassword != "" {
		if app.DebugPassword == "" || !auth.CheckTokenHash(creds.DebugPassword, app.DebugPassword) {
			return nil, &auth.AuthError{Status: http.StatusUnauthorized, Message: "invalid debug password"}
		}
		log.Warn().Str("app", app.ClientID).Msg("scrape debug mode used")
		used, err := s.repo.IncrementDebugUsage(utcDay(), app.ID)
		if err != nil {
			return nil, &auth.AuthError{Status: http.StatusInternalServerError, Message: "debug mode unavailable"}
		}
		if used > maxDebugCallsPerDay {
			s.record(app.ID, subject.SoftwareName, "rate_limited")
			return nil, &auth.AuthError{Status: http.StatusTooManyRequests, Message: "debug daily limit exceeded"}
		}
		_ = s.repo.IncrementDebugCalls(app.ID)
		_ = s.repo.RecordSoftwareOutcome(app.ID, subject.SoftwareName, "debug")
		subject.Debug = true
		subject.ForceUsed = creds.ForceUsed
		subject.ForceRateLimit = creds.ForceRateLimit
		if creds.ForceThreads != nil && *creds.ForceThreads > 0 {
			subject.Threads = *creds.ForceThreads
			subject.DailyLimit = *creds.ForceThreads * repository.DailyGamesPerThread
		}
	}

	if subject.Debug && subject.ForceRateLimit {
		s.record(app.ID, subject.SoftwareName, "rate_limited")
		return nil, &auth.AuthError{Status: http.StatusTooManyRequests, Message: "rate limit exceeded (debug)"}
	}
	if !s.allowSubject(subject) {
		s.record(app.ID, subject.SoftwareName, "rate_limited")
		return nil, &auth.AuthError{Status: http.StatusTooManyRequests, Message: "rate limit exceeded"}
	}
	return subject, nil
}

// record persists a scrape outcome for the developer dashboard (per app and per
// software). Failures are logged but never break the request.
func (s *ScrapeService) record(appID uuid.UUID, software, outcome string) {
	if err := s.repo.RecordScrapeOutcome(appID, outcome); err != nil {
		log.Warn().Err(err).Str("outcome", outcome).Msg("failed to record scrape outcome")
	}
	if err := s.repo.RecordSoftwareOutcome(appID, software, outcome); err != nil {
		log.Warn().Err(err).Str("outcome", outcome).Msg("failed to record software outcome")
	}
}

// RecordOutcome exposes outcome recording to handlers.
func (s *ScrapeService) RecordOutcome(subject *auth.ScrapeSubject, outcome string) {
	if subject == nil || subject.ClientDBID == uuid.Nil {
		return
	}
	s.record(subject.ClientDBID, subject.SoftwareName, outcome)
}

// resolveSoftwareName uses the client-supplied softname, falling back to the
// developer app's name. It is trimmed and capped to keep the stats dimension
// bounded.
func resolveSoftwareName(name, fallback string) string {
	name = strings.TrimSpace(name)
	if name == "" {
		name = fallback
	}
	if len(name) > 120 {
		name = name[:120]
	}
	return name
}

// resolveUser validates a user credential, which may be a personal API key or an
// existing user JWT.
func (s *ScrapeService) resolveUser(credential string) (*models.User, error) {
	if strings.HasPrefix(credential, auth.APIKeyPrefix) {
		prefix := credential
		if len(prefix) > auth.APIKeyPrefixLen {
			prefix = prefix[:auth.APIKeyPrefixLen]
		}
		key, err := s.repo.GetUserAPIKeyByPrefix(prefix)
		if err != nil || !auth.CheckTokenHash(credential, key.KeyHash) {
			return nil, &auth.AuthError{Status: http.StatusUnauthorized, Message: "invalid user API key"}
		}
		if key.LastUsedAt == nil || time.Since(*key.LastUsedAt) > time.Minute {
			_ = s.repo.TouchUserAPIKeyLastUsed(key.ID)
		}
		user, err := s.repo.GetUserByID(key.UserID)
		if err != nil {
			return nil, &auth.AuthError{Status: http.StatusUnauthorized, Message: "invalid user credential"}
		}
		if s.requireVerified && !user.EmailVerified {
			return nil, &auth.AuthError{Status: http.StatusForbidden, Message: "email not verified"}
		}
		return user, nil
	}

	claims, err := auth.ParseUserToken(s.jwtSecret, credential)
	if err != nil {
		return nil, &auth.AuthError{Status: http.StatusUnauthorized, Message: "invalid user credential"}
	}
	user, err := s.repo.GetUserByID(claims.UserID)
	if err != nil {
		return nil, &auth.AuthError{Status: http.StatusUnauthorized, Message: "invalid user credential"}
	}
	if s.requireVerified && !user.EmailVerified {
		return nil, &auth.AuthError{Status: http.StatusForbidden, Message: "email not verified"}
	}
	return user, nil
}

// preCheckRPM is the generous per-app cap applied before the optional user
// credential is resolved, bounding DB lookups from bogus credentials. It uses
// the maximum thread count so it never throttles a legitimate user.
func (s *ScrapeService) preCheckRPM() int {
	return progression.MaxThreads() * s.rpmPerThread
}

// allowSubject applies the per-minute rate limit for the resolved subject:
// registered users are keyed by user id and get threads * rpmPerThread, guests
// are keyed by the developer app and get the guest thread count.
func (s *ScrapeService) allowSubject(subject *auth.ScrapeSubject) bool {
	key := "app:" + subject.ClientID
	if !subject.IsGuest() {
		key = "user:" + subject.UserID.String()
	}
	return s.limiterFor(key, subject.Threads*s.rpmPerThread).Allow()
}

// limiterFor returns (or lazily creates) the token-bucket limiter for a key.
// Idle entries are evicted after 15 minutes so the map stays bounded without
// ever wiping active buckets. A bucket is rebuilt when its rpm changes (e.g. a
// user's thread count changed with XP or a donation).
func (s *ScrapeService) limiterFor(key string, rpm int) *rate.Limiter {
	s.mu.Lock()
	defer s.mu.Unlock()
	if len(s.limiters) > 10000 {
		cutoff := time.Now().Add(-15 * time.Minute)
		for k, e := range s.limiters {
			if e.last.Before(cutoff) {
				delete(s.limiters, k)
			}
		}
	}
	if e, ok := s.limiters[key]; ok {
		e.last = time.Now()
		if e.rpm == rpm {
			return e.lim
		}
	}
	l := rate.NewLimiter(rate.Limit(float64(rpm)/60.0), rpm)
	s.limiters[key] = &limiterEntry{lim: l, rpm: rpm, last: time.Now()}
	return l
}

// ListSystems returns the metadata system catalog.
func (s *ScrapeService) ListSystems() ([]models.MetadataSystem, error) {
	return s.meta.ListMetadataSystems()
}

// ListFamilies returns the broad system families (e.g. "arcade") with counts.
func (s *ScrapeService) ListFamilies() ([]models.MetadataFamily, error) {
	return s.meta.ListFamilies()
}

// ListGroups returns the system groups (e.g. "mame-fbneo") with counts.
func (s *ScrapeService) ListGroups() ([]models.MetadataGroup, error) {
	return s.meta.ListGroups()
}

// parenTagRegex and bracketTagRegex strip filename tags such as "(USA)" or
// "[!]" before a name search, mirroring how a scraper client names ROMs.
var (
	parenTagRegex   = regexp.MustCompile(`\([^)]*\)`)
	bracketTagRegex = regexp.MustCompile(`\[[^\]]*\]`)
)

// resolveSystems turns the query selector into the list of systems to search.
// Exactly one of SystemID, Family or Group must be set; a family/group expands
// to all its systems (e.g. "arcade" -> every arcade board, "mame-fbneo" -> the
// boards that run on MAME/FBNeo).
func (s *ScrapeService) resolveSystems(q models.ScrapeGameQuery) ([]string, error) {
	systemID := strings.TrimSpace(q.SystemID)
	family := strings.TrimSpace(q.Family)
	group := strings.TrimSpace(q.Group)

	set := 0
	for _, v := range []string{systemID, family, group} {
		if v != "" {
			set++
		}
	}
	if set == 0 {
		return nil, fmt.Errorf("system_id, family or group is required")
	}
	if set > 1 {
		return nil, fmt.Errorf("system_id, family and group are mutually exclusive")
	}

	switch {
	case systemID != "":
		sys, err := s.repo.GetMetadataSystem(systemID)
		if err != nil {
			return nil, fmt.Errorf("unknown system_id %q", systemID)
		}
		// A virtual system owns no games: it resolves to its group (when set) or
		// its family, so the catalog stays free of duplicated games (e.g. "arc"
		// covers every arcade board).
		if sys.Virtual {
			if g := strings.TrimSpace(sys.Group); g != "" {
				ids, err := s.meta.ListSystemIDsByGroup(g)
				if err != nil {
					return nil, err
				}
				if len(ids) > 0 {
					return ids, nil
				}
			}
			if f := strings.TrimSpace(sys.Family); f != "" {
				ids, err := s.meta.ListSystemIDsByFamily(f)
				if err != nil {
					return nil, err
				}
				if len(ids) > 0 {
					return ids, nil
				}
			}
			return nil, fmt.Errorf("virtual system %q aggregates no systems", systemID)
		}
		return []string{systemID}, nil
	case family != "":
		ids, err := s.meta.ListSystemIDsByFamily(family)
		if err != nil {
			return nil, err
		}
		if len(ids) == 0 {
			return nil, fmt.Errorf("unknown family %q", family)
		}
		return ids, nil
	default:
		ids, err := s.meta.ListSystemIDsByGroup(group)
		if err != nil {
			return nil, err
		}
		if len(ids) == 0 {
			return nil, fmt.Errorf("unknown group %q", group)
		}
		return ids, nil
	}
}

// FindGames resolves the query into a single game. The lookup is hash-first: a
// ROM hash (scoped to the selected system or family) is tried first, and when it
// does not match and a name is present the search falls back to the name. It
// returns the game (nil when nothing matched) and how it was matched ("hash" or
// "name").
func (s *ScrapeService) FindGames(q models.ScrapeGameQuery) (*models.ScrapeGame, string, error) {
	systemIDs, err := s.resolveSystems(q)
	if err != nil {
		return nil, "", err
	}
	if len(systemIDs) > maxSystemsPerRequest {
		return nil, "", fmt.Errorf("selector expands to too many systems (%d, max %d)", len(systemIDs), maxSystemsPerRequest)
	}

	name := cleanGameName(q.Name)

	hasHash := q.CRC != "" || q.MD5 != "" || q.SHA1 != "" || q.SHA256 != ""
	if hasHash {
		var games []models.Game
		for _, systemID := range systemIDs {
			found, err := s.meta.LookupGame(q.CRC, q.MD5, q.SHA1, q.SHA256, systemID)
			if err != nil {
				return nil, "", err
			}
			games = append(games, found...)
		}
		if len(games) > 0 {
			// A hash can match several entries (e.g. a base game and its hacks);
			// prefer the official one, and use the name to disambiguate when the
			// client sent both.
			return s.oneGame(bestMatch(games, name).ID, q), "hash", nil
		}
		// A hash miss with no name to fall back on is a genuine not-found.
		if name == "" {
			return nil, "hash", nil
		}
	}

	if name == "" {
		return nil, "", fmt.Errorf("name is required")
	}
	var candidates []models.Game
	for _, systemID := range systemIDs {
		found, _, err := s.meta.SearchGames(name, systemID, q.Type, "", maxGamesLimit, 0)
		if err != nil {
			return nil, "", err
		}
		candidates = append(candidates, found...)
	}
	best := bestMatch(candidates, name)
	if best == nil {
		return nil, "name", nil
	}
	return s.oneGame(best.ID, q), "name", nil
}

// cleanGameName normalizes a filename-style game name so a ROM name matches
// the catalog: it strips the file extension and parenthesized or bracketed tags
// (region, revision, [!], ...) and collapses whitespace.
func cleanGameName(name string) string {
	name = strings.TrimSpace(name)
	if name == "" {
		return ""
	}
	// Bound the length before the search so huge names cannot explode into
	// thousands of LIKE predicates.
	if r := []rune(name); len(r) > maxScrapeNameLen {
		name = string(r[:maxScrapeNameLen])
	}
	// Drop a trailing file extension (e.g. ".sfc", ".zip").
	if i := strings.LastIndex(name, "."); i > 0 {
		ext := name[i+1:]
		if ext != "" && !strings.ContainsAny(ext, " /\\") && len(ext) <= 5 {
			name = name[:i]
		}
	}
	name = parenTagRegex.ReplaceAllString(name, " ")
	name = bracketTagRegex.ReplaceAllString(name, " ")
	return strings.Join(strings.Fields(name), " ")
}

// oneGame loads a game's full detail, maps it to the scrape payload and bumps
// its scrape counter. It returns nil when the game cannot be loaded.
func (s *ScrapeService) oneGame(id uuid.UUID, q models.ScrapeGameQuery) *models.ScrapeGame {
	detail, err := s.meta.GetGame(id, "")
	if err != nil {
		return nil
	}
	out := s.toScrapeGame(detail, q)
	out.Scrapes = s.bumpScrape(id)
	return &out
}

// bumpScrape increments the game's scrape counter and returns the new count.
func (s *ScrapeService) bumpScrape(gameID uuid.UUID) int64 {
	if s.repo == nil {
		return 0
	}
	n, err := s.repo.IncrementGameScrape(gameID)
	if err != nil {
		log.Warn().Err(err).Str("game", gameID.String()).Msg("failed to increment game scrape")
		return 0
	}
	return n
}

// bestMatch picks the most relevant game. For a name search it scores the name
// match (exact first, then prefix, then substring); for a hash lookup (empty
// query) it just prefers base games and higher ratings. It returns nil for an
// empty list.
func bestMatch(games []models.Game, query string) *models.Game {
	if len(games) == 0 {
		return nil
	}
	q := strings.ToLower(strings.TrimSpace(query))
	best := &games[0]
	bestScore := -1
	for i := range games {
		g := &games[i]
		score := typeBonus(g.Type) + g.Rating
		if q != "" {
			score += nameScore(g.Name, q)
		}
		if score > bestScore {
			bestScore = score
			best = g
		}
	}
	return best
}

// nameScore ranks how well a game name matches the query.
func nameScore(name, q string) int {
	n := strings.ToLower(strings.TrimSpace(name))
	switch {
	case n == q:
		return 1000
	case strings.HasPrefix(n, q):
		return 500
	case strings.Contains(n, q):
		return 100
	default:
		return 0
	}
}

// typeBonus prefers official/base games over hacks and homebrew.
func typeBonus(t string) int {
	switch t {
	case "base":
		return 20
	case "homebrew":
		return 10
	default:
		return 0
	}
}

// PopularGames returns the most scraped games, optionally scoped to a system.
func (s *ScrapeService) PopularGames(systemID string, limit int) ([]models.PopularGame, error) {
	if limit <= 0 {
		limit = defaultPopularLimit
	}
	if limit > maxPopularLimit {
		limit = maxPopularLimit
	}
	systemID = strings.TrimSpace(systemID)
	if systemID != "" {
		if _, err := s.repo.GetMetadataSystem(systemID); err != nil {
			return nil, fmt.Errorf("unknown system_id %q", systemID)
		}
	}
	return s.repo.ListPopularGames(systemID, limit)
}

// toScrapeGame maps an internal game detail into the public scraping payload,
// resolving media object keys into public CDN URLs and optionally filtering the
// media kinds. The ROM list is only included when requested (`roms=true`);
// otherwise just the count is returned to keep the payload light.
func (s *ScrapeService) toScrapeGame(d *models.GameDetail, q models.ScrapeGameQuery) models.ScrapeGame {
	want := map[string]bool{}
	for _, k := range q.Media {
		if k != "" {
			want[k] = true
		}
	}

	media := make([]models.ScrapeMedia, 0, len(d.Media))
	for _, m := range d.Media {
		if len(want) > 0 && !want[m.Kind] {
			continue
		}
		media = append(media, models.ScrapeMedia{
			Kind: m.Kind,
			URL:  s.meta.PublicURL(m.ObjectKey),
			Mime: m.Mime,
			Size: m.Size,
		})
	}

	out := models.ScrapeGame{
		ID:           d.ID,
		SystemID:     d.SystemID,
		SystemName:   d.SystemName,
		Name:         d.Name,
		Region:       d.Region,
		ReleaseYear:  d.ReleaseYear,
		ReleaseMonth: d.ReleaseMonth,
		Publisher:    d.Publisher,
		Developer:    d.Developer,
		Genre:        d.Genre,
		Rating:       d.Rating,
		Type:         d.Type,
		RomCount:     len(d.Roms),
		Media:        media,
		Descriptions: s.descriptionsByLang(d.Game),
	}

	if len(d.Roms) > 0 {
		out.RomName = d.Roms[0].Name
	}

	if q.IncludeRoms {
		out.Roms = make([]models.ScrapeRom, 0, len(d.Roms))
		for _, r := range d.Roms {
			out.Roms = append(out.Roms, models.ScrapeRom{
				Name: r.Name, Size: r.Size, CRC: r.CRC, MD5: r.MD5,
				SHA1: r.SHA1, SHA256: r.SHA256, Region: r.Region,
			})
		}
	}
	return out
}

// descriptionsByLang builds the per-language description map: the base English
// description plus every enabled language's translation (empty when missing).
func (s *ScrapeService) descriptionsByLang(game models.Game) map[string]string {
	out := map[string]string{"en": game.Description}
	if s.repo == nil {
		return out
	}

	langs, err := s.repo.ListLanguages()
	if err != nil {
		return out
	}
	translations, err := s.repo.GameDescriptionsByLang(game.ID)
	if err != nil {
		translations = nil
	}
	for _, l := range langs {
		if l.Code == "en" {
			continue
		}
		out[l.Code] = translations[l.Code]
	}
	return out
}

// ConsumeQuota increments the daily quota for the subject and returns the
// resulting quota state. It returns ErrQuotaExceeded when the limit is reached.
func (s *ScrapeService) ConsumeQuota(subject *auth.ScrapeSubject) (*models.ScrapeQuota, error) {
	day := utcDay()
	subjectType, subjectID := usageKey(subject)

	var used int
	if subject.Debug && subject.ForceUsed != nil {
		// Debug override: report the forced counter without touching the real one.
		used = *subject.ForceUsed
	} else {
		var err error
		used, err = s.repo.IncrementScrapeUsage(day, subjectType, subjectID)
		if err != nil {
			return nil, err
		}
	}

	quota := buildQuota(subject.DailyLimit, used)
	if used > subject.DailyLimit {
		return quota, ErrQuotaExceeded
	}
	return quota, nil
}

// Account returns the current subject and its quota state without consuming it.
func (s *ScrapeService) Account(subject *auth.ScrapeSubject) (*models.ScrapeAccount, error) {
	day := utcDay()
	subjectType, subjectID := usageKey(subject)
	used, err := s.repo.GetScrapeUsage(day, subjectType, subjectID)
	if err != nil {
		return nil, err
	}
	acct := &models.ScrapeAccount{
		Subject: subject.Kind,
		Client:  models.ScrapeClient{ID: subject.ClientID, Name: subject.ClientName},
		Quota:   *buildQuota(subject.DailyLimit, used),
	}
	if !subject.IsGuest() {
		acct.User = &models.ScrapeUser{Username: subject.Username, Threads: subject.Threads}
	}
	return acct, nil
}

// usageKey returns the (subject_type, subject_id) pair used by the quota table.
// Guest quota is keyed by the developer app's owner, so creating more apps does
// not multiply the universal daily limit.
func usageKey(subject *auth.ScrapeSubject) (string, string) {
	if subject.IsGuest() {
		return "guest", subject.ClientOwnerID.String()
	}
	return "user", subject.UserID.String()
}

// buildQuota computes the quota payload, clamping remaining at zero.
func buildQuota(limit, used int) *models.ScrapeQuota {
	remaining := limit - used
	if remaining < 0 {
		remaining = 0
	}
	return &models.ScrapeQuota{
		DailyLimit: limit,
		Used:       used,
		Remaining:  remaining,
		ResetsAt:   utcDay().Add(24 * time.Hour),
	}
}

// utcDay returns the current UTC calendar date at midnight.
func utcDay() time.Time {
	now := time.Now().UTC()
	return time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, time.UTC)
}
